# -*- coding: utf-8 -*-

from openerp.osv import osv, fields
#from openerp.addons.topologia.model import municipios, parroquias

class Consejo(osv.Model):
	_name = "consejocomunal.consejo"
	
	_columns = {
		#Inicio de la seccion I (Identificacion Geografica)
		'fecha_r' : fields.date(string="Fecha de Realización", required=True),
		'nombre_emp' : fields.char(string="Nombre del Empadronador", size=25, required=True),
		'municipio' : fields.selection((('1','Libertador'),('2','Valencia'),('3','San Diego'),('4','Carlos Arvelo')),"Municipio", required=False),
		'parroquia' : fields.selection((('1','Libertador'),('2','Valencia'),('3','San Diego'),('4','Carlos Arvelo')),"Parroquia", required=False),
		'localidad' : fields.char(string="Localidad", size=100, required=True),
		'direccion' : fields.char(string="Dirección", size=256, required=True),
		#Inicio de la Seccion II (Area Organizativa del Consejo Comunal)
		'nombre_consejo' : fields.char(string="Nombre del Consejo Comunal", size=50, required=True),
		'legalizacion' : fields.selection((('1','SÍ'),('0','NO')),"Consejo Comunal Legalizado", required=True),
		'numero_reg' : fields.integer(string="Número de registro del Consejo", required=True),
		'conformacion' : fields.selection((('1','SÍ'),('0','NO')),"Consejo Comunal Conformado", required=True),
		'conformacion_proceso' : fields.selection((('1','SÍ'),('0','NO')),"Consejo Comunal en Proceso de Conformación", required=True),
		'vocerias_vencidas' : fields.selection((('1','SÍ'),('0','NO')),"Consejo Comunal con vocerias vencidas", required=True),
		'vocerias_vigentes' : fields.selection((('1','SÍ'),('0','NO')),"Consejo Comunal con vocerias vigentes", required=True),
		'origen' : fields.selection((('1','Indígena'),('2','Rural'),('3','Urbana')),"Origen del Consejo Comunal", required=True),
		'integracion_batalla' : fields.selection((('1','SÍ'),('0','NO')),"Integración a sala de Batalla Social", required=True),
		'comuna_construccion' : fields.selection((('1','SÍ'),('0','NO')),"¿Pertenece a Comuna en Construcción?", required=True),
		'reforma_consejos' : fields.selection((('1','Todas las personas'),('2','Algunas de las personas'),('3','Pocas personas'),('4','Ninguna de las personas')),"Conocimiento de Reforma de Consejos", required=True),
		#Inicio de la seccion III (Caracteristicas Demograficas)
		'cantidad_hab' : fields.integer(string="Cantidad de habitantes en el ámbito geográfico",required=True),
		'num_hombres' : fields.integer(string="Número de hombres", required=True),
		'num_mujeres' : fields.integer(string="Número de mujeres", required=True),
		'num_familias' : fields.integer(string="Número de familias", required=True),
		'num_viviendas' : fields.integer(string="Número de viviendas", required=True),
		'num_ninos' : fields.integer(string="¿Cuántos niños?", required=True),
		'num_ninas' : fields.integer(string="¿Cuántas niñas?", required=True),
		'num_adolescentes' : fields.integer(string="¿Cuántos adolescentes?", required=True),
		'num_adultos' : fields.integer(string="¿Cuántos adultos?", required=True),
		'num_adultos_mayores' : fields.integer(string="Número de adultos mayores de 60 años", required=True),
		'num_pers_discapacidad' : fields.integer(string="Número de personas con discapacidad permanente", required=True),
		'madres_solteras' : fields.selection((('1','SÍ'),('0','NO')),"Madres solteras como única fuente de sustento familiar", required=True),
		'num_madres_solteras' :fields.integer(string="Número de madres solteras como único sustento familiar",required=True),
		'num_madres_solteras_des' : fields.integer(string="¿Cuántas de esas madres solteras están desocupadas?", required=True),
		#Inicio de la seccion IV (Area Organizativa del Consejo Comunal)
		'alma_mater' : fields.boolean(string="Alma Mater"),
		'ribas' : fields.boolean(string="Ribas"),
		'robinson' : fields.boolean(string="Robinson"),
		'robinsonII' : fields.boolean(string="RobinsonII"),
		'robinsonIII' : fields.boolean(string="RobinsonIII"),
		'sucre' : fields.boolean(string="Sucre"),
		'escuelas_bolivarianas' : fields.selection((('1','SÍ'),('0','NO')), "Escuelas Bolivarianas", required=True),
		'escuelas_bol_ope' : fields.boolean(string="Operativo"),
		'simoncito' : fields.selection((('1','SÍ'),('0','NO')), "Simoncito", required=True),
		'simoncito_ope' : fields.boolean(string="Operativo"),
		'escuelas_oficiales' : fields.selection((('1','SÍ'),('0','NO')), "Escuelas Oficiales", required=True),
		'escuelas_ofi_ope' : fields.boolean(string="Operativo"),
		'aldeas_univeritarias' : fields.selection((('1','SÍ'),('0','NO')), "Aldeas Universitarias", required=True),
		'aldeas_uni_ope' : fields.boolean(string="Operativo"),
		'universidad_estatal' : fields.selection((('1','SÍ'),('0','NO')), "Universidad del Estado", required=True),
		'universidad_est_ope' : fields.boolean(string="Operativo"),
		'universidad_privada' : fields.selection((('1','SÍ'),('0','NO')), "Universidad Privada", required=True),
		'universidad_pri_ope' : fields.boolean(string="Operativo"),
		'nucleos_universitario' : fields.selection((('1','SÍ'),('0','NO')), "Núcleos Universitarios", required=True),
		'nucleos_uni_ope' : fields.boolean(string="Operativo"),
		'escuelas_robinson' : fields.selection((('1','SÍ'),('0','NO')), "Escuelas Robinsonianas", required=True),
		'escuelas_robin_ope' : fields.boolean(string="Operativo"),
		'inces' : fields.selection((('1','SÍ'),('0','NO')), "INCES", required=True),
		'inces_ope': fields.boolean(string="Operativo"),
		'analfabetas' : fields.integer(string="",size=11, required=True),
		'escue_poder_popular' : fields.selection((('1','SÍ'),('0','NO')), "", required=True),
		'participacion_voceros' : fields.selection((('1','SÍ'),('0','NO')), "", required=True),
		'cuantos_voceros_part' : fields.integer("", size=11, required=False),
		'plan_r_lectura' : fields.selection((('1','SÍ'),('0','NO')), "", required=True),
		'otros_espacios' : fields.selection((('1','SÍ'),('0','NO')), "", required=True),
		'tema_mas_leido' : fields.many2one('consejocomunal.temas_lectura', 'Temas', required=True),
		'libros_gratuitos' : fields.selection((('1','SÍ'),('0','NO')), "", required=False), 
		#Inicio de la seccion V (Caracteristicas Economicas)
		'ocupacion1' : 	fields.many2one('consejocomunal.ocupaciones', 'Ocupación1', required=True),
		'ocupacion2' : 	fields.many2one('consejocomunal.ocupaciones', 'Ocupación2', required=True),	
		'ocupacion3' : 	fields.many2one('consejocomunal.ocupaciones', 'Ocupación3', required=True),
		'potencialidad1' : fields.many2one('consejocomunal.potencialidades', 'Potencialidad1', required=True),	
		'potencialidad2' : fields.many2one('consejocomunal.potencialidades', 'Potencialidad2', required=True),	
		'potencialidad3' : fields.many2one('consejocomunal.potencialidades', 'Potencialidad3', required=True),
		'desocupados15' : fields.integer(string="", size=11, required=True),
		#Inicio de la sección VI (Características de los Proyectos Comunitarios)
		'proyectos_ultimo_anyo' : fields.selection((('1','SÍ'),('0','NO')), "", required=False),
		'numero_proyectos' : fields.integer(string="", size=11, required=True),
		'numero_proy_socioproduc' : fields.integer(string="", size=11, required=True),
		#Áreas de proyectos
		'agr_gan_caza_sil' : fields.boolean(string="Agricultura, ganadería, caza, silvicultura"),
		'pesca' : fields.boolean(string="Pesca"),
		'minas' : fields.boolean(string="Explotación de minas y canteras"),
		'ind_manufactura' : fields.boolean(string="Industrias	manufactureras"),
		'elect_gas_agua' : fields.boolean(string="Suministro de electricidad, gas y agua"),
		'construccion' : fields.boolean(string="Construcción"),
		'comercio' : fields.boolean(string="Comercio al mayor y al por menor"),
		'rep_automotores' : fields.boolean(string="Reparación de automotores"),
		'personal_enceres' : fields.boolean(string="Efectos personales y enceres domésticos"),
		'hotel_res': fields.boolean(string="Hoteles y restaurantes"),
		'trans_com' : fields.boolean(string="Transporte y comunicaciones"),
		'inmob_alquiler' : fields.boolean(string="Actividades inmobiliarias, empresariales y de alquiler"),
		#Situación de proyectos
		'en_proyecto' : fields.integer(string="En proyecto", size=11, required=False),	
		'en_ejecucion' : fields.integer(string="En ejecución", size=11, required=False),
		'ejecutado' : fields.integer(string="Ejecutado", size=11, required=False),
		'en_tramite' : fields.integer(string="En trámites administrativos institucionales", size=11, required=False),
		'en_elaboracion' : fields.integer(string="En elaboración", size=11, required=False),
		'proyectos_recursos' : fields.integer(string="", size=11, required=True),
		#Fuentes de financiamiento
		'gobernacion' : fields.boolean(string="Gobernación"),
		'alcaldia' : fields.boolean(string="Alcaldía"),
		'entes_priv' : fields.boolean(string="Entes privados"),
		'entes_est' : fields.boolean(string="Entes del estado"), 
		'ministerios' : fields.boolean(string="Ministerios"),
		'fondemi' : fields.boolean(string="FONDEMI"),
		'safonacc' : fields.boolean(string="SAFONACC"),
		'fundacomunal' : fields.boolean(string="Fundacomunal"),
		'otro_esp' : fields.char(string="Otro (especifique)", size=100, required=False),
		#Inicio de la sección VII (Características de las Misiones Sociales)
		'arbol' : fields.boolean(string="Árbol"),
		'b_a_deportivo' : fields.boolean(string="Barrio Adentro Deportivo"),
		'b_adentro_I' : fields.boolean(string="Barrio Adentro I"),
		'b_adentro_II' : fields.boolean(string="Barrio Adentro II"),
		'b_adentro_II' : fields.boolean(string="Barrio Adentro III"),
		'ciencia' : fields.boolean(string="Ciencia"),
		'cristo' : fields.boolean(string="Cristo"),
		'cultura' : fields.boolean(string="Cultura"),
		'energetica' : fields.boolean(string="Energética"),
		'guaicaipuro' : fields.boolean(string="Guaicaipuro"),
		'habitat' : fields.boolean(string="Habitat"),
		'madres_b' : fields.boolean(string="Madres del Barrio"),
		'mercal' : fields.boolean(string="Mercal"),
		'milagro' : fields.boolean(string="Milagro"),
		'miranda' : fields.boolean(string="Miranda"),
		'musica' : fields.boolean(string="Música"),
		'negra_hipolita' : fields.boolean(string="Negra Hipólita"),
		'n_barrio' : fields.boolean(string="Niños y niñas del barrio"), 
	}
